// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpsGLApLsLFjNQ-uxLwh7Y2F7Ad-uNLWE',
    appId: '1:771263121579:web:360b9f9ba1c043e1558fee',
    messagingSenderId: '771263121579',
    projectId: 'eyego-movies-app',
    authDomain: 'eyego-movies-app.firebaseapp.com',
    storageBucket: 'eyego-movies-app.firebasestorage.app',
    measurementId: 'G-32RRKFFTL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkqN6iqpR-p_31rWdZZTvBzRsQvBPFrk',
    appId: '1:771263121579:android:afef04d28919d3f5558fee',
    messagingSenderId: '771263121579',
    projectId: 'eyego-movies-app',
    storageBucket: 'eyego-movies-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7ChzjQYJzE9Ta7FwI_cf_06x6kYXDIE',
    appId: '1:771263121579:ios:11d33d24bb28ac81558fee',
    messagingSenderId: '771263121579',
    projectId: 'eyego-movies-app',
    storageBucket: 'eyego-movies-app.firebasestorage.app',
    iosBundleId: 'com.example.eyegoMoviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP7ChzjQYJzE9Ta7FwI_cf_06x6kYXDIE',
    appId: '1:771263121579:ios:11d33d24bb28ac81558fee',
    messagingSenderId: '771263121579',
    projectId: 'eyego-movies-app',
    storageBucket: 'eyego-movies-app.firebasestorage.app',
    iosBundleId: 'com.example.eyegoMoviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpsGLApLsLFjNQ-uxLwh7Y2F7Ad-uNLWE',
    appId: '1:771263121579:web:31db0101393f5e83558fee',
    messagingSenderId: '771263121579',
    projectId: 'eyego-movies-app',
    authDomain: 'eyego-movies-app.firebaseapp.com',
    storageBucket: 'eyego-movies-app.firebasestorage.app',
    measurementId: 'G-52LBK8ZYRT',
  );
}
